apps/blog/urls.py
from django.urls import path
from .views import blog_detail,blog_list,about


app_name='blog'

urlpatterns=[
    path('', blog_list, name='list'),

    path('detail/<int:pk>/', blog_detail, name='detail'),

    path('about/',about,name='about')


]

apps/cart/urls.py
from django.urls import path
from .views import add_wishlist,my_wishlist,add_cart,my_cart_view,plus_quantity,minus_quantity,delete_cart_item_view,checkout_view


app_name='carts'

urlpatterns=[
    path('add-wishlist/',add_wishlist,name='add_wishlist'),
    path('wishlist/',my_wishlist,name="my_wishlist"),
    path('add-cart/',add_cart,name="add-cart"),
    path('my-cart/',my_cart_view,name="my_cart"),
    path('minus-quantity/', minus_quantity, name='minus-quantity'),
    path('plus-quantity/', plus_quantity, name='plus-quantity'),
    path('delete-cart-item-view/', delete_cart_item_view, name='delete-cart-item-view'),
    path('checkout/',checkout_view,name='checkout')
]

apps/contacts/urls.py
from .views import contact_view
from django.urls import path

app_name='contact'

urlpatterns=[
    path('', contact_view, name='contact'),




]

apps/product/urls.py
from django.urls import path

from .views import *

app_name = 'products'
urlpatterns = [
    # path('search/',base_view,name="base"),
    path('', product_view),
    path('shop/', shop_view),
    path('detail/<int:pk>/', shop_detailed_view, name='detail'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                path('accounts/', include('allauth.urls')),
                path('accounts/',include('apps.accounts.urls')),
                path('admin/', admin.site.urls),
                path('blog/', include('apps.blog.urls', namespace='blog')),
                path('', include('apps.product.urls', namespace='home')),
                path('contact/', include('apps.contacts.urls', namespace='contact')),
                path('carts/', include('apps.cart.urls', namespace='carts')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your model


class Timestamp(models.Model):
    crated_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True


class Tag(Timestamp):
    title=models.CharField(max_length=50)
    def __str__(self):
        return self.title
class Post(Timestamp):
    title=models.CharField(max_length=100)
    image=models.ImageField(upload_to='blog/',null=True)
    tags=models.ManyToManyField(Tag,blank=True)
    content=models.TextField()
    username=User.username


    def __str__(self):
        return self.title

class CommentModel(models.Model):
    name=models.CharField(max_length=100)
    phone=models.CharField(max_length=30)
    email=models.EmailField()
    message=models.TextField()

apps/cart/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save

# from apps.product.models import Product
from apps.product.models import Product


class WishList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'Wishlist of {self.user.username} (id:{self.id})'


class Cart(models.Model):
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    is_ordered = models.BooleanField(default=False)

    @property
    def get_cart_items(self):
        cart_items = self.cart_items.all()
        total = sum([item.quantity for item in cart_items])
        return total

    @property
    def get_total_price(self):
        cart_items = self.cart_items.all()
        total = sum([item.get_total for item in cart_items])
        return total

    def __str__(self):
        return f'order of {self.client} (id: {self.id})'


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True, related_name="cart_items")
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField(null=True, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def get_total(self):
        return self.quantity*self.product.price


class Order(models.Model):
    STATUS = (
        (0, 'NEW'),
        (1, 'PROCESS'),
        (2, 'DELIVERED'),
        (3, 'CANCELLED'),

    )

    transaction_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    phone = models.CharField(max_length=21)
    note = models.TextField(null=True, blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    addres=models.CharField(max_length=50)

    def __str__(self):
        return f'order of {self.client} (id: {self.id}) | {self.transaction_id}'

apps/contacts/models.py
from django.db import models

# Create your models here.
class ContactModel(models.Model):
    name=models.CharField(max_length=100)
    email=models.EmailField()
    message=models.TextField()


    def __str__(self):
        return self.name

apps/blog/forms.py
from django import forms

from apps.blog.models import CommentModel


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Your name'
        self.fields['email'].widget.attrs['placeholder'] = 'Your email'
        self.fields['phone'].widget.attrs['placeholder'] = 'Your number'
        self.fields['message'].widget.attrs['placeholder'] = 'Your message'

apps/contacts/forms.py
from apps.contacts.models import ContactModel
from django import forms

class ContactForm(forms.ModelForm):
    class Meta:
        model = ContactModel
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs['placeholder'] = 'Your name'
        self.fields['email'].widget.attrs['placeholder'] = 'Your email'
        self.fields['message'].widget.attrs['placeholder'] = 'Your message'

apps/blog/views.py
from django.shortcuts import render

from .models import Post, Tag
from .forms import CommentForm


# Create your views here.


# Create your views here.
def blog_list(request):

    blogs = Post.objects.order_by('-id')[:9]

    ctx = {
        'blogs': blogs,
    }
    return render(request, 'blog.html', ctx)


def blog_detail(request,pk):
    blogs = Post.objects.order_by('-id')
    blog = Post.objects.get(id=pk)

    tag = Tag.objects.all()
    form = CommentForm(request.POST or None)
    if form.is_valid():
        form.save()

    ctx = {
        'blogs': blogs,
        'tag': tag,
        'blog': blog,
        'form':form
    }
    try:
        prev = Post.objects.get(id=pk-1)
        ctx['prev'] = prev
    except:
        pass
    try:
        next = Post.objects.get(id=pk+1)
        ctx['next'] = next
    except:
        pass

    return render(request, 'blog-details.html', ctx)

def about(request):
    return render(request,'about.html')

apps/contacts/views.py
from django.shortcuts import render

from .forms import ContactForm


# Create your views here.
def contact_view(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()

    ctx = {
        'form': form
    }
    return render(request, 'contact.html', ctx)

templates/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/img.png' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Our Blog</h2>
                </div>
            </div>
        </div>
    </section>


    <section class="blog spad">

        <div class="container">

            <div class="row">
                {% for blog in blogs %}

                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ blog.image.url }}"></div>
                            <div class="blog__item__text">
                                {#                        <span><img src="{{ blog.image.url }}"#}
                                {#                                   alt=""> {{ blog.crated_at }}</span>#}
                                <h5><a href="{% url 'blog:detail' blog.id %}">{{ blog.title|slice:':49' }}</a></h5>
                                <a href="{% url 'blog:detail' blog.id %}">Read More</a>
                            </div>

                        </div>

                    </div>
                {% endfor %}

            </div>

        </div>


    </section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% for collection in collections %}
    <section class="hero">
        <div class="hero__slider owl-carousel">
            <div class="hero__items set-bg" data-setbg="{% static 'img/img_2.png' %}">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5 col-lg-7 col-md-8">
                            <div class="hero__text">
                                <h6>{{ collection.season }}</h6>
                                <h2>{{ collection.name }}</h2>
                                <p>{{ collection.desriptions }}</p>
                                <a href="#" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                                <div class="hero__social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-pinterest"></i></a>
                                    <a href="#"><i class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="hero__items set-bg" data-setbg="img/hero/hero-2.jpg">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-5 col-lg-7 col-md-8">
                            <div class="hero__text">
                                <h6>Summer Collection</h6>
                                <h2>Fall - Winter Collections 2030</h2>
                                <p>A specialist label creating luxury essentials. Ethically crafted with an unwavering
                                    commitment to exceptional quality.</p>
                                <a href="#" class="primary-btn">Shop now <span class="arrow_right"></span></a>
                                <div class="hero__social">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-pinterest"></i></a>
                                    <a href="#"><i class="fa fa-instagram"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="banner spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 offset-lg-4">
                    <div class="banner__item">
                        <div class="banner__item__pic">
                            <img src="{% static 'img/banner/xbanner-1.jpg.pagespeed.ic.nZTivFR0IB.jpg' %}" alt="">
                        </div>
                        <div class="banner__item__text">
                            <h2>Clothing Collections 2030</h2>
                            <a href="#">Shop now</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="banner__item banner__item--middle">
                        <div class="banner__item__pic">
                            <img src="{% static 'img/banner/xbanner-2.jpg.pagespeed.ic.pbodzVtQKw.jpg' %}" alt="">
                        </div>
                        <div class="banner__item__text">
                            <h2>Accessories</h2>
                            <a href="#">Shop now</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7">
                    <div class="banner__item banner__item--last">
                        <div class="banner__item__pic">
                            <img src="{% static 'img/banner/xbanner-3.jpg.pagespeed.ic.53F3MtBYv-.jpg' %}" alt="">
                        </div>
                        <div class="banner__item__text">
                            <h2>Shoes Spring 2030</h2>
                            <a href="#">Shop now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% endfor %}


    <section class="product spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="filter__controls">
                        {% for category in categories_name %}
                            <li data-filter=".{{ category.normalize_title }}">{{ category }}</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>

            <div class="row product__filter">
                {% for product in product %}
                    <div class="col-lg-3 col-md-6 col-sm-6 col-md-6 col-sm-6 mix {{ product.category.normalize_title }}">
                        <div class="product__item">
                            <div class="product__item__pic set-bg"
                                 data-setbg="{{ product.image.url }}">
                                <span class="label">{{ product.condition }}</span>
                                <ul class="product__hover">

                                    {% if request.user.is_authenticated %}
                                        <li><a class="add-wishlist" data-product="{{ product.id }}"><img
                                                src="{% static 'img/icon/xheart.png.pagespeed.ic.eX6BmaqN_X.png' %}"
                                                alt=""></a>
                                        </li>
                                        {#                                    <li><a href="#"><img#}
                                        {#                                            src="{% static 'img/icon/xcompare.png.pagespeed.ic.UIWeUFOM61.png' %}"#}
                                        {#                                            alt=""> <span>Compare</span></a>#}
                                        {#                                    </li>#}
                                        <li><a class="#"><img
                                                src="{% static 'img/icon/xsearch.png.pagespeed.ic.y-8fLDHdJm.png' %}"
                                                alt=""></a>
                                        </li>
                                    {% else %}
                                        <p style="background-color:beige;color: #343a40"><a href="accounts/login">
                                            firstly you should log in</a></p>
                                    {% endif %}
                                </ul>
                            </div>

                            <div class="product__item__text">
                                <h6>{{ product.name }}</h6>
                                <a href="" class="add-cart" data-product="{{ product.id }}">+ Add To Cart</a>
                                <div class="rating">
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                    <i class="fa fa-star-o"></i>
                                </div>
                                <h5>{{ product.price }}</h5>
                                <div class="product__color__select">
                                    <label for="pc-1">
                                        <input type="radio" id="pc-1" # {{ product.color }}>
                                    </label>
                                    <label class="active black" for="pc-2">
                                        <input type="radio" id="pc-2">
                                    </label>
                                    <label class="grey" for="pc-3">
                                        <input type="radio" id="pc-3">
                                    </label>

                                </div>


                            </div>

                        </div>
                    </div>
                {% endfor %}

            </div>


        </div>

    </section>


    <section class="categories spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="categories__text">
                        <h2>Clothings Hot <br/> <span>Shoe Collection</span> <br/> Accessories</h2>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="categories__hot__deal">
                        <img src="{% static 'img/xproduct-sale.png.pagespeed.ic.JhWwWRcVR-.png' %}" alt="">
                        <div class="hot__deal__sticker">
                            <span>Sale Of</span>
                            <h5>$29.99</h5>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 offset-lg-1">
                    <div class="categories__deal__countdown">
                        <span>Deal Of The Week</span>
                        <h2>Multi-pocket Chest Bag Black</h2>
                        <div class="categories__deal__countdown__timer" id="countdown">
                            <div class="cd-item">
                                <span>3</span>
                                <p>Days</p>
                            </div>
                            <div class="cd-item">
                                <span>1</span>
                                <p>Hours</p>
                            </div>
                            <div class="cd-item">
                                <span>50</span>
                                <p>Minutes</p>
                            </div>
                            <div class="cd-item">
                                <span>18</span>
                                <p>Seconds</p>
                            </div>
                        </div>
                        <a href="#" class="primary-btn">Shop now</a>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="instagram spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="instagram__pic">
                        <div class="instagram__pic__item set-bg"
                             data-setbg="{% static 'img/instagram/instagram-1.jpg' %}"></div>
                        <div class="instagram__pic__item set-bg"
                             data-setbg="{% static 'img/instagram/instagram-2.jpg' %}"></div>
                        <div class="instagram__pic__item set-bg"
                             data-setbg="{% static 'img/instagram/instagram-3.jpg' %}"></div>
                        <div class="instagram__pic__item set-bg"
                             data-setbg="{% static 'img/instagram/instagram-4.jpg' %}"></div>
                        <div class="instagram__pic__item set-bg"
                             data-setbg="{% static 'img/instagram/instagram-5.jpg' %}"></div>
                        <div class="instagram__pic__item set-bg"
                             data-setbg="{% static 'img/instagram/instagram-6.jpg' %}"></div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="instagram__text">
                        <h2>Instagram</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua.</p>
                        <h3>#Male_Fashion</h3>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="latest spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title">
                        <span>Latest News</span>
                        <h2>Fashion New Trends</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                {% for blog_latest_item in blogs %}
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="blog__item">
                            <div class="blog__item__pic set-bg" data-setbg="{{ blog_latest_item.image.url }}"></div>
                            <div class="blog__item__text">
                                <h5>
                                    <a href="{% url 'blog:detail' blog_latest_item.id %}"> {{ blog_latest_item.title|slice:':49' }} </a>
                                </h5>
                                <a href="{% url 'blog:detail' blog_latest_item.id %}">Read More</a>
                            </div>

                        </div>

                    </div>

                {% endfor %}
            </div>

        </div>

    </section>


{% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Malefashion|Profile Page</title>
    <style>@import url("https://fonts.googleapis.com/css2?family=Poppins:weight@100;200;300;400;500;600;700;800&display=swap");

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    body {
        background-color: #545454;
        font-family: "Poppins", sans-serif;
        font-weight: 300;
    }

    .container {
        height: 100vh;


    }

    .card {

        width: 380px;
        border: none;
        border-radius: 15px;
        padding: 8px;
        background-color: #fff;
        position: relative;
        height: 370px;
    }

    .upper {

        height: 100px;

    }

    .upper img {

        width: 100%;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;

    }

    .user {
        position: relative;
    }

    .profile img {


        height: 80px;
        width: 80px;
        margin-top: 2px;


    }

    .profile {

        position: absolute;
        top: -50px;
        left: 38%;
        height: 90px;
        width: 90px;
        border: 3px solid #fff;

        border-radius: 50%;

    }

    .follow {

        border-radius: 15px;
        padding-left: 20px;
        padding-right: 20px;
        height: 35px;
    }

    .stats span {

        font-size: 29px;
    }</style>

</head>
{% for profile in profile %}
    <body style="background-color: #545454">

    <div class="container d-flex justify-content-center align-items-center"
         style="text-align: center;padding-left: 480px;position: absolute; ">

        <div class="card">

            <div class="upper">

                <img src="https://i.imgur.com/Qtrsrk5.jpg" class="img-fluid">

            </div>

            <div class="user text-center">

                <div class="profile">


                    <img src="{{ profile.avatar.url }}" style="border-radius: 40px; padding-bottom: 1px"
                         class="rounded-circle" width="100">

                </div>

            </div>


            <div class="mt-5 text-center">

                <h4 style="line-height: 65px;margin-bottom: 0.5px" class="mb-0">{{ profile }}</h4>
                <span class="text-muted d-block mb-2">{{ profile.bio }}</span>

                <button class="btn btn-primary btn-sm follow">Follow</button>


                <div class="row">

                    <div class="col">
                        <h6 class="col-6 col-sm-3">Items in wishlist</h6>
                        <span>{{ request.user.wishlist_set.all.count }} </span>

                    </div>


                    <div class="col order-12">
                        <h6 class="col-6 col-sm-3">Items in cart</h6>
                        <span>{{ cart.get_cart_items }}</span>

                    </div>

                    <a style="color: black" href="/accounts/logout/">Log out</a>


                </div>

            </div>

        </div>

    </div>

    </body>
{% endfor %}

</html>

templates/shopping-cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <section class="breadcrumb-option">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb__text">
                        <h4>Shopping Cart</h4>
                        <div class="breadcrumb__links">
                            <a href="/">Home</a>
                            <a href="shop.html">Shop</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <section class="shopping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="shopping__cart__table">
                        <table>
                            <thead>
                            <tr>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for item in cart.cart_items.all %}
                                <tr>
                                    <td class="product__cart__item">
                                        <div class="product__cart__item__pic">
                                            <img style="width:100px" src="{{ item.product.image.url }}" alt="">
                                        </div>
                                        <div class="product__cart__item__text">
                                            <h6>{{ item.product.name }}</h6>
                                            <h5>{{ item.product.price }}</h5>
                                        </div>
                                    </td>
                                    <td class="quantity__item">
                                        <div class="quantity">
                                            <div class="pro-qty-2">
                                                <input class="quantity" disabled data-cart_item_id="{{ item.id }}"
                                                       type="text" value="{{ item.quantity }}">
                                            </div>
                                        </div>
                                    </td>
                                    <td class="cart__price">{{ item.get_total }}</td>
                                    <td class="cart__close"><i class="fa fa-close"></i></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn">
                                <a href="/shop/">Continue Shopping</a>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6">
                            <div class="continue__btn update__btn">
                                <a href="/carts/my-cart/"><i class="fa fa-spinner"></i> Update cart</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="cart__discount">
                        <h6>Discount codes</h6>
                        <form action="#">
                            <input type="text" placeholder="Coupon code">
                            <button type="submit">Apply</button>
                        </form>
                    </div>
                    <div class="cart__total">
                        <h6>Cart total</h6>
                        <ul>
                            <li>Total <span>{{ cart.get_total_price }}</span></li>
                        </ul>
                        <a href="{% url 'carts:checkout' %}?cart_id={{ cart.id }}" class="primary-btn">Proceed to checkout</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}